;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-buffer
        dabbrev-expand
        esprit/beginning-of-line
        exit-recursive-edit
        indent-for-tab-command
        keyboard-escape-quit
        mc--insert-number-and-increase
        org-delete-char
        org-self-insert-command
        org-yank
        ))

(setq mc/cmds-to-run-once
      '(
        backward-sexp
        comment-line
        consult-yank-pop
        dabbrev-completion
        embark-act
        end-of-buffer
        end-of-visual-line
        forward-sexp
        goto-line
        helpful-callable
        pixel-scroll-precision
        ))
