;;; esprit-themes.el --- A set of esprit color themes -*- lexical-binding: t; -*-

;; Copyright (C) 2026 Luke Inglis

;; Author: Luke Inglis <ld.inglis@gmail.com>
;; Maintainer: Luke Inglis <ld.inglis@gmail.com>>
;; URL: https://github.com/ludamillion/reasonable-colors.el
;; Created: 11th September 2026
;; Version: 0.1.0
;; Keywords: colors
;; Package-Requires: ((emacs "24"))

;;; Commentary:

;;; Code:

(defconst reasonable-color-palette
  '((gray . ((one   . "#f6f6f6")
             (two   . "#e2e2e2")
             (three . "#8b8b8b")
             (four  . "#6f6f6f")
             (five  . "#3e3e3e")
             (six   . "#222222")))
    (rose . ((one   . "#fff7f9")
             (two   . "#ffdce5")
             (three . "#ff3b8d")
             (four  . "#db0072")
             (five  . "#800040")
             (six   . "#4c0023")))
    (raspberry  . ((one   . "#fff8f8")
                   (two   . "#ffdddf")
                   (three . "#ff426c")
                   (four  . "#de0051")
                   (five  . "#82002c")
                   (six   . "#510018")))
    (red . ((one   . "#fff8f6")
            (two   . "#ffddd8")
            (three . "#ff4647")
            (four  . "#e0002b")
            (five  . "#830014")
            (six   . "#530003")))
    (orange . ((one   . "#fff8f5")
               (two   . "#ffded1")
               (three . "#fd4d00")
               (four  . "#cd3c00")
               (five  . "#752100")
               (six   . "#401600")))
    (cinnamon . ((one   . "#fff8f3")
                 (two   . "#ffdfc6")
                 (three . "#d57300")
                 (four  . "#ac5c00")
                 (five  . "#633300")
                 (six   . "#371d00")))
    (amber . ((one   . "#fff8ef")
              (two   . "#ffe0b2")
              (three . "#b98300")
              (four  . "#926700")
              (five  . "#523800")
              (six   . "#302100")))
    (yellow . ((one   . "#fff9e5")
               (two   . "#ffe53e")
               (three . "#9c8b00")
               (four  . "#7d6f00")
               (five  . "#463d00")
               (six   . "#292300")))
    (lime . ((one   . "#f7ffac")
             (two   . "#d5f200")
             (three . "#819300")
             (four  . "#677600")
             (five  . "#394100")
             (six   . "#222600")))
    (chartreuse . ((one   . "#e5ffc3")
                   (two   . "#98fb00")
                   (three . "#5c9b00")
                   (four  . "#497c00")
                   (five  . "#264500")
                   (six   . "#182600")))
    (green . ((one   . "#e0ffd9")
              (two   . "#72ff6c")
              (three . "#00a21f")
              (four  . "#008217")
              (five  . "#004908")
              (six   . "#062800")))
    (emerald . ((one   . "#dcffe6")
                (two   . "#5dffa2")
                (three . "#00a05a")
                (four  . "#008147")
                (five  . "#004825")
                (six   . "#002812")))
    (aquamarine . ((one   . "#daffef")
                   (two   . "#42ffc6")
                   (three . "#009f78")
                   (four  . "#007f5f")
                   (five  . "#004734")
                   (six   . "#00281b")))
    (teal . ((one   . "#d7fff7")
             (two   . "#00ffe4")
             (three . "#009e8c")
             (four  . "#007c6e")
             (five  . "#00443c")
             (six   . "#002722")))
    (cyan . ((one   . "#c4fffe")
             (two   . "#00fafb")
             (three . "#00999a")
             (four  . "#007a7b")
             (five  . "#004344")
             (six   . "#002525")))
    (powder . ((one   . "#dafaff")
               (two   . "#8df0ff")
               (three . "#0098a9")
               (four  . "#007987")
               (five  . "#004048")
               (six   . "#002227")))
    (sky . ((one   . "#e3f7ff")
            (two   . "#aee9ff")
            (three . "#0094b4")
            (four  . "#007590")
            (five  . "#00404f")
            (six   . "#001f28")))
    (cerulean . ((one   . "#e8f6ff")
                 (two   . "#b9e3ff")
                 (three . "#0092c5")
                 (four  . "#00749d")
                 (five  . "#003c54")
                 (six   . "#001d2a")))
    (azure . ((one   . "#e8f2ff")
              (two   . "#c6e0ff")
              (three . "#008fdb")
              (four  . "#0071af")
              (five  . "#003b5e")
              (six   . "#001c30")))
    (blue . ((one   . "#f0f4ff")
             (two   . "#d4e0ff")
             (three . "#0089fc")
             (four  . "#006dca")
             (five  . "#00386d")
             (six   . "#001a39")))
    (indigo . ((one   . "#f3f3ff")
               (two   . "#deddff")
               (three . "#657eff")
               (four  . "#0061fc")
               (five  . "#00328a")
               (six   . "#001649")))
    (violet . ((one   . "#f7f1ff")
               (two   . "#e8daff")
               (three . "#9b70ff")
               (four  . "#794aff")
               (five  . "#2d0fbf")
               (six   . "#0b0074")))
    (purple . ((one   . "#fdf4ff")
               (two   . "#f7d9ff")
               (three . "#d150ff")
               (four  . "#b01fe3")
               (five  . "#660087")
               (six   . "#3a004f")))
    (magenta . ((one   . "#fff3fc")
                (two   . "#ffd7f6")
                (three . "#f911e0")
                (four  . "#ca00b6")
                (five  . "#740068")
                (six   . "#44003c")))
    (pink . ((one   . "#fff7fb")
             (two   . "#ffdcec")
             (three . "#ff2fb2")
             (four  . "#d2008f")
             (five  . "#790051")
             (six   . "#4b0030")))
    )
  "Associative array of the Reasonable Color colors names to value palettes."
  )

(defconst reasonable-colors--angle-mapping
  '((rose       . 0)
    (raspberry  . 15)
    (red        . 30)
    (orange     . 45)
    (cinnamon   . 60)
    (amber      . 75)
    (yellow     . 90)
    (lime       . 105)
    (chartreuse . 120)
    (green      . 135)
    (emerald    . 150)
    (aquamarine . 165)
    (teal       . 180)
    (cyan       . 195)
    (powder     . 210)
    (sky        . 225)
    (cerulean   . 240)
    (azure      . 255)
    (blue       . 270)
    (indigo     . 285)
    (violet     . 300)
    (purple     . 315)
    (magenta    . 330)
    (pink       . 345))
  "Reasonable Colors are 15° apart on the color wheel with `rose' at 0°.")

(defun reasonable-colors--rotate-cw (start offset)
  "Returns the degree term OFFSET degrees clockwise from START."
  (mod (+ start offset) 360))

(defun reasonable-colors--rotate-ccw (start offset)
  "Returns the degree term OFFSET degrees counter-clockwise from START."
  (mod (- start offset) 360))

(defun reasonable-colors-color-at-stop (deg)
  "Returns the color name for the color located at DEG on the reasonable color wheel."
  (car (rassoc deg reasonable-colors--angle-mapping)))

(defun reasonable-colors-stop-for-color (color)
  "Returns the `stop' on the reasonable color wheel in degrees for COLOR."
  (cdr (assoc color reasonable-colors--angle-mapping)))

(defun reasonable-colors-get (name shade)
  "Returns the color indexed by SHADE for the color NAME."
  (cdr (assoc shade (assoc name reasonable-color-palette))))

(defun reasonable-colors-complement (name)
  ""
  (let ((deg (reasonable-colors-stop-for-color name)))
    (when deg
        (reasonable-colors-color-at-stop (reasonable-colors--rotate-cw deg 180)))))

(defun reasonable-colors-split-complement (name)
  ""
  (let ((base (reasonable-colors-stop-for-color (reasonable-colors-complement name))))
    (when base
      (list
       (reasonable-colors-color-at-stop (reasonable-colors--rotate-cw base 15))
       (reasonable-colors-color-at-stop (reasonable-colors--rotate-ccw base 15))))))

(defun reasonable-colors-analogous (name)
  ""
  (let ((base (reasonable-colors-stop-for-color name)))
    (when base
      (list
       (reasonable-colors-color-at-stop (reasonable-colors--rotate-cw base 15))
       (reasonable-colors-color-at-stop (reasonable-colors--rotate-ccw base 15))))))

(defun reasonable-colors-triadic (name)
  ""
  (let ((base (reasonable-colors-stop-for-color name)))
    (when base
      (list
       (reasonable-colors-color-at-stop (reasonable-colors--rotate-cw base 120))
       (reasonable-colors-color-at-stop (reasonable-colors--rotate-ccw base 120))))))

(defun reasonable-colors-tetradic (name)
  ""
  (let ((base (reasonable-colors-stop-for-color name)))
    (when base
      (list
       (reasonable-colors-color-at-stop (reasonable-colors--rotate-cw base 90))
       (reasonable-colors-color-at-stop (reasonable-colors--rotate-cw base 180))
       (reasonable-colors-color-at-stop (reasonable-colors--rotate-cw base 270))))))

(reasonable-colors-get 'pink 'one)
(reasonable-colors-complement 'rose)
(reasonable-colors-split-complement 'rose)
(reasonable-colors-analogous 'rose)
(reasonable-colors-triadic 'rose)
(reasonable-colors-tetradic 'rose)

(provide 'reasonable-colors)
